language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: black-request.surge.sh/
  skip_cleanup: true
  on:
    branch: main
